---
title: "Resources"
author: "Psych Methods Support"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Resources

## Columbia-Specific Resources

---

- [Columbia Psychology scientific computing users Slack group](https://join.slack.com/t/cu-psych-r-users/shared_invite/enQtMjk5MTExNjkxOTkwLTY2MjJkMGY1ZmU1MzM0ZTA0NTM2ZDJjZjFjMzU4YmRjZDJiMWQyMjJkMzVkMjc0YTE0OTg4ZmU2NjdlYzZiNjk){target="_blank"})

## Full, Freestanding General-Use R Tutorials

---

### Mainly base R tutorials

- [Cookbook for R: Basics of data cleaning, analysis and graphing](http://www.cookbook-r.com/){target="_blank"}

### Tidyverse tutorials

- [Hadley Wickham's R for Data Science online textbook](http://r4ds.had.co.nz/){target="_blank"}
- [Michael C. Frank's psychology-specific tidyverse tutorial, adapted from R for Data Science](https://github.com/mcfrank/tidyverse-tutorial/blob/master/tidyverse_tutorial.Rmd){target="_blank"}

### Syllabi for courses taught in R

You can work along with these; course materials should be linked in the syllabi.
- [Karen LaRocque's syllabus for Stanford's undergrad intro to stats in psychology class, winter 2017](http://web.stanford.edu/class/psych10/schedule/index.html){target="_blank"}

## Various R Cheat Sheets

---

- [A very large list of cheatsheets, tutorials and books on R](https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books/){target="_blank"}

<div class="row">
<div class="col-md-6">
<iframe
src="https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf"
frameborder="0"
width="95%"
height="400px"
scrolling="auto">
</iframe>
</div>
<div class="col-md-6">
<iframe
src="https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf"
frameborder="0"
width="95%"
height="400px"
scrolling="auto">
</iframe>
</div>
</div>

[Base R reference card for many different uses](https://cran.r-project.org/doc/contrib/Short-refcard.pdf){target="_blank"}

[Hadley Wickham's intro to the tidy data framework](https://vita.had.co.nz/papers/tidy-data.pdf){target="_blank"}

## Graphing

---

- [GGplot Visualization Guide (with code)](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html){target="_blank"}
- [Palette of all named colors that you can use in ggplot](http://sape.inf.usi.ch/quick-reference/ggplot2/colour){target="_blank"}

## Working with Version Control

---

- [A tutorial for integrating RStudio and Github](http://happygitwithr.com/){target="_blank"}

## Programming

---

This section is for those who would like to write their own functions, packages, etc. and require a more computer-science-y understanding of R as a programming language.

- [Hadley Wickham's Advanced R online textbook](http://adv-r.had.co.nz/){target="_blank"}
- [Hadley Wickham's R Packages online textbook](http://r-pkgs.had.co.nz/){target="_blank"}
