---
title: "Columbia Psychology Scientific Computing"
author: "Psych Methods Support"
date: "8/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitrBootstrap)
options(rstudio.markdownToHTML =
  function(inputFile, outputFile) {
    require(knitrBootstrap)
    knit_bootstrap_md(input=inputFile, output=outputFile)
  }
)
```

<hr>

## Fall 2020 Workshop

**Instructors:** Paul A. Bloom, Emily Nakkawita, Jonathan Nicholas, Matt Siegelman, Hannah Tarder-Stoll, Monica Thieu

## General Information

This workshop develops and teaches the scientific computing skills needed to conduct psychological research. Its target audience is researchers who have little to no prior computational experience, and its lessons are psychology-specific, building on learners' existing knowledge to enable them to quickly apply skills learned to their own research.

**Who:** The course is aimed at graduate, postbac, and undergraduate students, as well as other researchers. You don't need to have any previous knowledge of the tools that will be presented at the workshop.

**Where:** Zoom (links to be provided upon confirmation of registration)<!--Butler Library 2nd floor (rooms TBD). Get directions with OpenStreetMap or Google Maps.-->

**When:** September 11, 18, 25, 2020

**Requirements:** Participants must participate using a laptop with a Mac, Linux, or Windows operating system (not a tablet, Chromebook, etc.) that they have administrative privileges on. They should have a few specific software packages installed (listed [below](https://cu-psych-computing.github.io/cu-psych-comp-tutorial/workshop/#setup)).

**Code of Conduct:** Everyone who participates in this workshop is required to conform to the [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html){target="_blank"}. This document also outlines how to report an incident if needed.

**Accessibility:** We are committed to making this workshop accessible to everybody. <!--The workshop organizers have checked that:

The room is wheelchair / scooter accessible.
Accessible restrooms are available.
-->Materials will be provided in advance of the workshop and large-print handouts are available if needed by notifying the organizers in advance. If we can help making learning easier for you (e.g., sign-language interpreters<!--, lactation facilities-->) please get in touch using the contact details below, and we will attempt to provide them.

**Contact:** Please email [psych-methods-support@columbia.edu](mailto:psych-methods-support@columbia.edu){target="_blank"} for more information.

---

## Surveys

Please be sure to complete these surveys before and after the workshop.

[Pre-Workshop Survey](https://docs.google.com/forms/d/e/1FAIpQLSchEOWieJF5F391L5-fSC4DBCAJ1hOIbIUWiAWqyfZC9gzBAQ/viewform?usp=sf_link){target="_blank"}

[Post-Workshop Survey](https://docs.google.com/forms/d/e/1FAIpQLSe4iqiAev5qqmQfoL7hxFVzlihEKzjthKv0wLOipsjaad88FQ/viewform?usp=sf_link){target="_blank"}

---

## Schedule

<div class="row">
  <div class="col-md-6">
    <h3>Session 1: R (9/11/20), Zoom</h3>
    <table class="table table-striped">
      <tr><td>Before starting</td><td><a href="https://docs.google.com/forms/d/e/1FAIpQLSchEOWieJF5F391L5-fSC4DBCAJ1hOIbIUWiAWqyfZC9gzBAQ/viewform?usp=sf_link" target="_blank">Pre-workshop survey</a></td></tr>
      <tr><td><b>9:00a</b> - 10:00a</td><td><a href="/R/1_programming/lessonPart0.html">Acquainting Yourself with RStudio</a></td></tr>
      <tr><td>10:00a - 12:30p</td><td><a href="/R/1_programming/lessonPart1.html">Intro to Programming and Data Cleaning in R, Part 1</a></td></tr>
      <tr><td>12:30p - 1:00p</td><td>Lunch</td></tr>
      <tr><td>1:00p - <b>3:00p</b></td><td><a href="/R/1_programming/lessonPart2.html">Intro to Programming and Data Cleaning in R, Part 2</a></td></tr>
    </table>
  </div>
  <div class="col-md-6">
    <h3>Session 2: R (9/18/20), Zoom</h3>
    <table class="table table-striped">
      <tr><td><b>10:00a</b> - 11:30a</td><td><a href="/R/3_descriptives/lesson.html">Data Manipulation in R, Part 1</a></td></tr>
      <tr><td>11:30a - 12:30p</td><td>Lunch</td></tr>
      <tr><td>12:30p - 1:30p</td><td>Data Manipulation in R, Part 2</td></tr>
      <tr><td>1:30p - 3:30p</td><td><a href="/R/4_plotting/lesson.html">Plotting in R with <code>ggplot2</code></a></td></tr>
    </table>
  </div>
  <div class="col-md-6">
    <h3>Session 3: Python (9/25/20), Zoom</h3>
    <table class="table table-striped">
      <tr><td><b>9:00a</b> - 10:30a</td><td><a href="/Python/1_r2PythonTranslation/2_introProgramming.html">Intro to Python for R Users</a></td></tr>
      <tr><td>10:30a - 12:00p</td><td><a href="/Python/2_dataCleaning/lesson.html">Data Cleaning in Python</a></td></tr>
      <tr><td>12:00p - 12:30p</td><td><a href="/Python/3_descriptives/lesson.html">Data Manipulation in Python, Part 1</a></td></tr>
      <tr><td>12:30p - 1:00p</td><td>Lunch</td></tr>
      <tr><td>1:00p - 2:00p</td><td>Data Manipulation in Python, Part 2</td></tr>
      <tr><td>2:00p - 4:00p</td><td><a href="/Python/4_plotting/lesson.html">Plotting in Python with <code>seaborn</code></a></td></tr>
      <tr><td>After finishing</td><td><a href="https://docs.google.com/forms/d/e/1FAIpQLSe4iqiAev5qqmQfoL7hxFVzlihEKzjthKv0wLOipsjaad88FQ/viewform?usp=sf_link," target="_blank">Post-workshop survey</a></td></tr>
    </table>
  </div>
</div>

### Session 1: R (9/11/20), Zoom

Before starting: <a href="https://docs.google.com/forms/d/e/1FAIpQLSchEOWieJF5F391L5-fSC4DBCAJ1hOIbIUWiAWqyfZC9gzBAQ/viewform?usp=sf_link" target="_blank">Pre-workshop survey</a>

<b>9:00a</b> - 10:00a: <a href="https://cu-psych-computing.github.io/cu-psych-comp-tutorial/R/1_programming/lessonPart0.html" target="_blank">Acquainting Yourself with RStudio</a>

10:00a - 12:30p: <a href="https://cu-psych-computing.github.io/cu-psych-comp-tutorial/R/1_programming/lessonPart1.html" target="_blank">Intro to Programming and Data Cleaning in R, Part 1</a>

12:30p - 1:00p: Lunch

1:00p - <b>3:00p</b>: <a href="https://cu-psych-computing.github.io/cu-psych-comp-tutorial/R/1_programming/lessonPart2.html" target="_blank">Intro to Programming and Data Cleaning in R, Part 2</a>

### Session 2: R (9/18/20), Zoom

<b>10:00a</b> - 11:30a: <a href="https://cu-psych-computing.github.io/cu-psych-comp-tutorial/R/3_descriptives/lesson.html" target="_blank">Data Manipulation in R, Part 1</a>

11:30a - 12:30p: Lunch

12:30p - 1:30p: Data Manipulation in R, Part 2

1:30p - 3:30p: <a href="https://cu-psych-computing.github.io/cu-psych-comp-tutorial/R/4_plotting/lesson.html" target="_blank">Plotting in R with <code>ggplot2</code></a>

### Session 3: Python (9/25/20), Zoom

<b>9:00a</b> - 10:30a: <a href="https://cu-psych-computing.github.io/cu-psych-comp-tutorial/python/1_r2PythonTranslation/2_introProgramming.html" target="_blank">Intro to Python for R Users</a>

10:30a - 12:00p: <a href="https://cu-psych-computing.github.io/cu-psych-comp-tutorial/python/2_dataCleaning/lesson.html" target="_blank">Data Cleaning in Python</a>

12:00p - 12:30p: <a href="https://cu-psych-computing.github.io/cu-psych-comp-tutorial/python/3_descriptives/lesson.html" target="_blank">Data Manipulation in Python, Part 1</a>

12:30p - 1:00p: Lunch

1:00p - 2:00p: Data Manipulation in Python, Part 2

2:00p - 4:00p: <a href="https://cu-psych-computing.github.io/cu-psych-comp-tutorial/python/4_plotting/lesson.html" target="_blank">Plotting in Python with <code>seaborn</code></a>

After finishing: <a href="https://docs.google.com/forms/d/e/1FAIpQLSe4iqiAev5qqmQfoL7hxFVzlihEKzjthKv0wLOipsjaad88FQ/viewform?usp=sf_link" target="_blank">Post-workshop survey</a>

---

## Setup

To participate in this workshop, you will need access to the software described below. In addition, you will need an up-to-date web browser.

We maintain a list of common issues that occur during installation as a reference for instructors that may be useful on the [Configuration Problems and Solutions wiki page](https://github.com/swcarpentry/workshop-template/wiki/Configuration-Problems-and-Solutions){target="_blank"}.

### R

[R](https://www.r-project.org/){target="_blank"} is a programming language that is especially powerful for data exploration, visualization, and statistical analysis. To interact with R, we use [RStudio](https://www.rstudio.com/){target="_blank"}.

#### Windows

[Video Tutorial](https://www.youtube.com/watch?v=q0PjTAylwoU){target="_blank"}

Install R by downloading and running [this .exe file](https://cran.r-project.org/bin/windows/base/release.htm){target="_blank"} from [CRAN](https://cran.r-project.org/index.html){target="_blank"}. Also, please install the [RStudio IDE](https://www.rstudio.com/products/rstudio/download/#download){target="_blank"}. Note that if you have separate user and admin accounts, you should run the installers as administrator (right-click on .exe file and select "Run as administrator" instead of double-clicking). Otherwise problems may occur later, for example when installing R packages.

#### MacOS

[Video Tutorial](https://www.youtube.com/watch?v=5-ly3kyxwEg){target="_blank"}

Install R by downloading and running [this .pkg file](https://cran.r-project.org/bin/macosx/R-latest.pkg){target="_blank"} from [CRAN](https://cran.r-project.org/index.html){target="_blank"}. Also, please install the [RStudio IDE](https://www.rstudio.com/products/rstudio/download/#download){target="_blank"}.

#### Linux

You can download the binary files for your distribution from [CRAN](https://cran.r-project.org/index.html){target="_blank"}. Or you can use your package manager (e.g. for Debian/Ubuntu to run `sudo apt-get install r-base`; and for Fedora run `sudo dnf install R`). Also, please install the [RStudio IDE](https://www.rstudio.com/products/rstudio/download/#download){target="_blank"}.

### Python

[Python](https://python.org/){target="_blank"} is a popular language for research computing, and great for general-purpose programming as well. Installing all of its research packages individually can be a bit difficult, so we recommend [Anaconda](https://www.anaconda.com/distribution/){target="_blank"}, an all-in-one installer.

Regardless of how you choose to install it, **please make sure you install Python version 3.x** (e.g., 3.6 is fine).

We will teach Python using the [Jupyter notebook](https://jupyter.org/){target="_blank"}, a programming environment that runs in a web browser. For this to work you will need a reasonably up-to-date browser. The current versions of the Chrome, Safari and Firefox browsers are all [supported](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#browser-compatibility){target="_blank"} (some older browsers, including Internet Explorer version 9 and below, are not).

#### Windows

[Video Tutorial](https://www.youtube.com/watch?v=xxQ0mzZ8UvA){target="_blank"}

Open [https://www.anaconda.com/download/#windows](https://www.anaconda.com/download/#windows){target="_blank"} with your web browser. Download the Python 3 installer for Windows. Then, install Python 3 using all of the defaults for installation _except_ make sure to check **Add Anaconda to my PATH environment variable**.

#### MacOS

[Video Tutorial](https://www.youtube.com/watch?v=TcSAln46u9U){target="_blank"}

Open [https://www.anaconda.com/download/#macos](https://www.anaconda.com/download/#macos){target="_blank"} with your web browser. Download the Python 3 installer for OS X. Then, install Python 3 using all of the defaults for installation.

#### Linux

Open [https://www.anaconda.com/download/#linux](https://www.anaconda.com/download/#linux){target="_blank"} with your web browser. Download the Python 3 installer for Linux.

**Please Note:** The installation requires using the shell. If you aren't comfortable doing the installation yourself stop here and contact [psych-methods-support@columbia.edu](mailto:psych-methods-support@columbia.edu){target="_blank"} for assistance.)

To proceed with installation:

1. Open a terminal window.

2. Type `bash Anaconda3` and then press <kbd>Tab</kbd>. The name of the file you just downloaded should appear. If it does not, navigate to the folder where you downloaded the file, for example with `cd Downloads`. Then, try again.

3. Press <kbd>Return</kbd>. You will follow the text-only prompts. To move through the text, press <kbd>Spacebar</kbd>. Type `yes` and press enter to approve the license. Press enter to approve the default location for the files. Type `yes` and press enter to prepend Anaconda to your `PATH` (this makes the Anaconda distribution the default Python).

4. Close the terminal window.
